packages:
  - 'packages/*'

onlyBuiltDependencies:
  - esbuild
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - oxlint
  - oxfmt
  - cpu-features
  - ssh2

minimumReleaseAge: 0

allowBuilds:
  cpu-features: true
  ssh2: true
